name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - '**.md'

env:
  BUNDLE_PATH: vendor/bundle

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      
      - name: Run linting
        run: ./bin/standardrb --no-fix

  test-import:
    runs-on: ubuntu-latest
    services:
      search:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
        ports:
          - 9200:9200
        env:
          "discovery.type": "single-node"
          "ES_JAVA_OPTS": "-Xms512m -Xmx512m"
          "xpack.security.enabled": "false"
        options: >-
          --health-cmd "curl --silent --fail http://localhost:9200/_cluster/health || exit 1"
          --health-start-period 30s
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v3

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Test Importing Ruby Documentation
        env:
          ELASTICSEARCH_URL: "http://localhost:9200"
        run: ./bin/rake "import:ruby[dev]"

  test:
    runs-on: ubuntu-latest
    services:
      search:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
        ports:
          - 9200:9200
        env:
          "discovery.type": "single-node"
          "ES_JAVA_OPTS": "-Xms512m -Xmx512m"
          "xpack.security.enabled": "false"
        options: >-
          --health-cmd "curl --silent --fail http://localhost:9200/_cluster/health || exit 1"
          --health-start-period 30s
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v3

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Yarn
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get -yqq install chromium-chromedriver
          yarn install --frozen-lockfile

      - name: Run Tests
        env:
          ELASTICSEARCH_URL: "http://localhost:9200"
        run: |
          ./bin/yarn build && ./bin/yarn build:css
          ./bin/rails test
